services:
  - type: web
    name: realtime-ohgiri
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn 
      --worker-class eventlet 
      --workers 1 
      --bind 0.0.0.0:10000
      --log-level debug 
      --timeout 300 
      wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000" 